### ISSUE TITLE
Add CLI interface

### ISSUE THREAD

**Issue by clemux** [archivy/archivy#108]
We should add a CLI interface for:

 - running archivy locally
 - configuring archivy (once #107 is done)
 - installing external dependencies like pandoc (currently pypandoc downloads and installs the pandoc binary without asking the user)
 
But also:

 - setup a new plugin (once #86 is done), for example adding a pocket account
 - adding a bookmark (useful for UNIX-like integration of various tools)
 - ...?
 
 As @srevinsaju suggested on discord, I think [Click](https://click.palletsprojects.com/en/7.x/) is a great choice. It's even used by Flask already (see: https://flask.palletsprojects.com/en/1.1.x/cli/)

**Comment by Uzay-G** [comment]
Completed :)
