### ISSUE TITLE
Links between objects

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#119]
Could be interesting to have a simple way for users to link between different objects

**Comment by Uzay-G** [comment]
Maybe we could use a pandoc filter

**Comment by Just-Insane** [comment]
it would be cool to have support for [backlinks](https://en.wikipedia.org/wiki/Backlink#Wikis), also known as bi-directional links (this is a good overview: https://maggieappleton.com/bidirectionals). Not sure if this should be a new issue or not?

**Comment by Uzay-G** [comment]
My idea here would be that you'd link from Page A -> B but it would be bidirectional as in when you visited B you'd see the link A -> B. I think this issue is for the same idea as the bidirectional links you bring up.

**Comment by Just-Insane** [comment]
Ah, yea it was unclear if this was just A -> B, or if B would reference back to A.

**Comment by BrianGilbert** [comment]
relevant and worth reading https://medium.com/swlh/welcome-to-the-note-taking-apocalypse-64a74481a5ab

**Comment by Uzay-G** [comment]
@BrianGilbert you mean I would put something like `[[Random Note]]` in one of my notes, and then it would automatically create notes?

I was thinking of adding some form of bidirectional tagging and at least one-way links.

One way links are easy to design / implement, I would just have to add something to the editor that lets me search for a note with its title and then link to it.

On the other hand, for bidirectional links, we could do this:

- Whenever you open a note, simply search for any incoming links. This option would require having search enabled (with ripgrep or elasticsearch), because otherwise it would be too slow. (preferred method)
- maintain some sort of log of links in the lightweight `TinyDB` database. This would be be more complex and would be a slower option, because we'd have to check for any discarded links whenever there is an edit.

> https://maggieappleton.com/bidirectionals

@Just-Insane this overview is really nice. i think I'm going to start working on adding backlinks :)

**Comment by Uzay-G** [comment]
What I have for now:
![random](https://user-images.githubusercontent.com/52892257/110252827-97dba980-7f87-11eb-8fc7-2fbdd5822de1.gif)

**Comment by BrianGilbert** [comment]
@Uzay-G that looks great, you may need to also show the folder somehow when selecting page,if I have identically named notes in different folders for instance

_"@BrianGilbert you mean I would put something like [[Random Note]] in one of my notes, and then it would automatically create notes?"_

Yes exactly this, as per many wiki's

**Comment by Uzay-G** [comment]
> @Uzay-G that looks great, you may need to also show the folder somehow when selecting page,if I have identically named notes in different folders for instance

If you look at the gif you'll see that it actually includes the id in the link, so it wouldn't be a problem.

> Yes exactly this, as per many wiki's

Hmm in that case I'd have to include folder information or something. I could also setup a way to redirect to/from the new note form. :thinking:

**Comment by Uzay-G** [comment]
Implemented in #218 and is in the last release :)
