### ISSUE TITLE
Integration with Foam?

### ISSUE THREAD

**Issue by Just-Insane** [archivy/archivy#128]
Would it be possible to integrate with [Foam](https://github.com/foambubble/foam)?

It is an open-source alternative to [Roam](https://roamresearch.com). It is designed to be a knowledge management tool in which files are stored in markdown, and includes nifty features like backlinks and graph overview.

This request is similar to #50 but for an open-source application.

**Comment by Uzay-G** [comment]
That is an interesting project but it would prove difficult to integrate it into archivy. 

However, I do want to work on adding these features to basically auto-group similar content with Natural Language Processing (#88) and add ways for people to create backlinks #119 by simply writing for example `#<id>` like github does.

That'd definitely be useful.

**Comment by Just-Insane** [comment]
My understanding was that Archivy was able to index markdown documents and allow full-text search of them? If that is the case, I don't think it would be too hard to integrate the two projects, I think both projects are working on adding plug-ins?

**Comment by Uzay-G** [comment]
Foam is specific to vs code and we wouldn't want to directly integrate it into the source, but we'd be happy to help with a plugin that bridged the two.

**Comment by Just-Insane** [comment]
Yea, that makes sense. I'll look into creating a plug-in to integrate the two. I think it would be a useful integration.

**Comment by Uzay-G** [comment]
I'll close this for now.
