### ISSUE TITLE
Look for full-text search engine that is easier to setup than Elasticsearch

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#13]
Elasticsearch is extremely powerful and flexible, but slightly hard to setup. 

Could be interesting to find a more lightweight yet still qualitative alternative.

**Comment by HarshaVardhanJ** [comment]
Take a look at this [SO post](https://stackoverflow.com/questions/737275/comparison-of-full-text-search-engine-lucene-sphinx-postgresql-mysql). The two main suggestions seem to be [Sphinx](http://sphinxsearch.com) and [Apache Solr](https://lucene.apache.org/solr/).

**Comment by jochenleidner** [comment]
Lucene is what I'd suggest, it's the actual search engine powering both Elastic and Solr. It can be used as a standalone library to index a set of files and to query the resulting index in just a few lines of Java code.

**Comment by Uzay-G** [comment]
@jochenleidner elasticsearch feels like overkill for a knowledge base, and so I wanted to use something a bit less bulky and difficult to set up. Is lucene a good fit for that?

**Comment by Uzay-G** [comment]
This could also be interesting as a lightweight python alternative to elasticsearch that uses sqlite: https://scout.readthedocs.io/en/latest/index.html

**Comment by jochenleidner** [comment]
Yes, compare e.g. the sizes of the packages: 305 MB (Elastic) and 80 MB (Lucene). In terms of complexity it's even more than a 4x win, IMHO.

In constrast, I don't recommend solutions based on relational databases; they aren't typically suitable for fast and compressing inverted file storage of textual structures, as they provide higher level abstractions like a relational query language layer and an ACID transaction layer that only cost you performance but the functionality of which isn't needed for this.

**Comment by pbronez** [comment]
It would be valuable to use a search engine written in Python, or at least packaged with pip/conda. This would facilitate deployment to environments that have a Python interpreter but not Docker or perhaps even root privileges. This is the case with many enterprise-managed devices found in companies and schools.

**Comment by jochenleidner** [comment]
Lucene is in Java, but there is a CLucene implementation in C++ (
http://clucene.sourceforge.net/ ), and C++ code is easier to integrate with
Python than Java.

**Comment by leram84** [comment]
I was going to suggest including elasticsearch in the docker container, but maybe not worth the issue if you're going to move to something else soon?

**Comment by Uzay-G** [comment]
I think we will probably go with giving an option to either use elasticsearch and the power that comes with it OR a native python library like Scout. @HarshaVardhanJ do you know how it would be potentially possible to integrate this into the docker image in the future?

**Comment by HarshaVardhanJ** [comment]
Will be adding Elasticsearch integration soon. Working on it.

**Comment by HarshaVardhanJ** [comment]
It would be possible, yes. I'll create a PR once I've got it up and running
on my local machine.

**Comment by Cybergate9** [comment]
Elastic's strength is simplicity in implementation for such a basic use case, although I hear what others are saying about simpler + python.
Two options seems like a reasonable compromise to expand deployment options for different folks :-)

**Comment by Uzay-G** [comment]
We need to work on this

**Comment by Uzay-G** [comment]
If anyone finds a python package that isn't too outdated that could accomplish this, that'd be amazing. I haven't found any yet.

**Comment by tonluong** [comment]
there's Bleve for Go
http://blevesearch.com/

**Comment by tonluong** [comment]
Also take a look at Fuse.js
https://fusejs.io/

Pure JS, browser or app can be indexer

**Comment by Uzay-G** [comment]
Fuse could be nice.

**Comment by Uzay-G** [comment]
This is pretty nice but it's also kind of limited: https://lunr.readthedocs.io/

**Comment by balki** [comment]
https://xapian.org/

**Comment by pirate** [comment]
We use Sonic over at ArchiveBox and it's served us well so far https://github.com/valeriansaliou/sonic, we also use ripgrep as a fallback for people who don't want to go through the trouble of setting up a long-running search backend. We tried Lunr and ElasticSolr and didn't have a great experience (the indexes were too large and unwieldy for big archives) but YMMV.

**Comment by Uzay-G** [comment]
Hmm I'll definitely check these out, and I've actually thought about using ripgrep before, does it work well?

**Comment by pirate** [comment]
Yeah, it's great on SSDs, not so great on HDDs. It's probably the most bang-for-bug minimalist search you can do since there's no indexing step, and you can install it easily via package manager on pretty much every OS, which is a stark contrast from something like elasticsearch/sonic where you have to set up a whole search backend.

**Comment by Uzay-G** [comment]
I've begun implementing a setup using ripgrep at #217. Still a work in progress but has been fairly easy to code.

**Comment by Uzay-G** [comment]
@pirate is sonic an effort to setup for your users, or is it pretty easy?

Ripgrep is nice but it's still a bit limited (not full-text).

**Comment by pirate** [comment]
Sonic is fairly easy, closer to ripgrep than elasticsearch in terms of setup difficulty. There is one config file, but the actual program is just a single executable with everything included, also runs well in docker.
