### ISSUE TITLE
Problem with Docker + ES

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#130]
A reddit user recently said:

> Hi tried running the app along with elastic search using docker-compose. The elasticsearch logs show the following,

> ElasticsearchException[Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]

> The archivy logs show it is just waiting for elastic search to start.

@HarshaVardhanJ we could easily solve this problem by simply adding `xpack.ml.enabled` -> false in the docker-compose, but then the filtering and quality of search would decrease.

Did you ever encounter this problem when using the docker-compose for ES?

**Comment by HarshaVardhanJ** [comment]
As per [this issue](https://issues.apache.org/jira/browse/FLINK-14126), this happens when Elasticsearch <= `1.11.0` is run on ARM architecture. They claim to have fixed it in version `1.11.0` and above. I'll try moving to Elasticsearch image to this version.

**Comment by Uzay-G** [comment]
@HarshaVardhanJ someone else has been having a problem with this, could you check the discord server, they asked a question there. I think the docker setup isn't up to date.

**Comment by hchasens** [comment]
For posterity, I'm referencing #13 here (migration away from Elastic).
