### ISSUE TITLE
Profile icon is not visible in dark mode

### ISSUE THREAD

**Issue by HarshaVardhanJ** [archivy/archivy#138]
When dark mode is toggled, the profile logo isn't visible as its colour is the same as the background colour in dark mode(black). Given below are the screenshots of the page in light and dark mode(have checked on multiple browsers):

Light Mode : 
![Light Mode](https://user-images.githubusercontent.com/34051768/100192297-b5748e00-2f17-11eb-8b1e-a3d589b36032.png)

Dark Mode : 
![Dark Mode](https://user-images.githubusercontent.com/34051768/100192306-bad1d880-2f17-11eb-870f-a22f8ddbe3e1.png)

**Comment by Uzay-G** [comment]
Good catch but this was fixed in #134. Should be good on the next version :+1:

**Comment by HarshaVardhanJ** [comment]
Alrighty. 👍
