### ISSUE TITLE
Error message when listing plugins on Web UI

### ISSUE THREAD

**Issue by HarshaVardhanJ** [archivy/archivy#143]
## Steps

* Installed `archivy_hn` plugin. (`pip3.9 install archivy_hn`)
* Started Archivy. (`archivy run`)
* Logged in.
* Clicked on `Plugins` link.
* Page shows `hn-sync` in list of plugins.

> Attached screenshot below:
![List of plugins](https://user-images.githubusercontent.com/34051768/100314928-b8d24d00-2fdd-11eb-81e2-fee24dbf9e76.png)

This generates the following error message in the logs:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/cli.py", line 556, in list_commands
    rv.update(info.load_app().cli.list_commands(ctx))
  File "/usr/local/lib/python3.9/site-packages/Flask-1.1.2-py3.9.egg/flask/cli.py", line 398, in load_app
    raise NoAppException(
flask.cli.NoAppException: Could not locate a Flask application. You did not provide the "FLASK_APP" environment variable, and a "wsgi.py" or "app.py" module was not found in the current directory.
172.17.0.1 - - [26/Nov/2020 06:15:38] "GET /plugins HTTP/1.1" 200 -
172.17.0.1 - - [26/Nov/2020 06:15:38] "GET /static/open_form.js HTTP/1.1" 304 -
172.17.0.1 - - [26/Nov/2020 06:15:38] "GET /static/post_and_read.js HTTP/1.1" 304 -
172.17.0.1 - - [26/Nov/2020 06:15:47] "GET /cli/hn-sync HTTP/1.1" 200 -
127.0.0.1 - - [26/Nov/2020 06:15:59] "GET / HTTP/1.1" 302 -
```

Also, what command am I supposed to select in the left pane(as is seen in the screenshot)?

**Comment by Uzay-G** [comment]
I'm really not sure - everything seems to be working fine but there's an error for some reason...
