### ISSUE TITLE
ADD: Helper command to auto-generate plugin directory with structure

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#152]

**Comment by vacom13** [comment]
@Uzay-G 
Might be a little too late lol but has this already been worked upon? I am an os newbie so still trying to figure this stuff out 😅.

**Comment by Uzay-G** [comment]
No it hasn't been implemented yet. Do you have any plugin ideas? I can explain the plugin directory structure if you'd like :)

**Comment by Uzay-G** [comment]
It would be a command like `archivy plugin new <plugin name>` that would then setup the directory with everything you need to create a plugin.

**Comment by vacom13** [comment]
Could you um point me towards some resources? I could refer too maybe. And yes, explaining the structure would be great help too! I actually am well a newbie programmer as well 😅. I assume that by plugins you imply something like jupyter lab for vs code or emmet for sublime text?

**Comment by Uzay-G** [comment]
Archivy plugins are extensions that use the archivy knowledge base's contents and add to it some extra functionality:

You can see the structure of an example plugin here: for the archivy-pocket plugin which allows you to download your pocket saved articles: https://github.com/archivy/archivy-pocket/

**Comment by vacom13** [comment]
Okay @Uzay-G I wish to have a go at it. Please assign this to me!

**Comment by Uzay-G** [comment]
Ok!

**Comment by vacom13** [comment]
@Uzay-G okay so I have been thinking about this a ton and would like some of your help. Please just guide me on whether this would be the correct way of approaching this. So as soon as I type "archivy plugin new <name>" it basically creates a "setup.py", a requirements.text and a directory consisting of  __init__.py as another pyton file as said in "plugind.md" file? Am I correct?

**Comment by Uzay-G** [comment]
Yeah it would create a new directory `<plugin_name>` with inside requirements.txt, setup.py and a sub directory with `__init__.py`

**Comment by vacom13** [comment]
@Uzay-G so I have basically implemented it as a plugin if thats cool? I have the code files ready with me right now which do exactly as specified. What do I do now? I checked plugins.md. Do I just publish it or idk. I wrote pretty basic code 😅.

**Comment by vacom13** [comment]
Okay cool

**Comment by vacom13** [comment]
@Uzay-G I have actually implemented this. However, could you guide me on creating the pr? Like do I create a new branch in my fork and then create a pr while comparing across forks and that would automatically create a new branch in the ustream?

**Comment by Uzay-G** [comment]
Yeah that's it. Put your changes on a branch of your fork and then you can open a PR onto this repo, comparing it to your fork's branch.

**Comment by vacom13** [comment]
Okay. I am doing it right away.

**Comment by Uzay-G** [comment]
Closing this, thanks again @vacom13
