### ISSUE TITLE
add a plugin command

### ISSUE THREAD

**Issue by srevinsaju** [archivy/archivy#165]
Add a plugin command that would automatically install the plugin by the bundle id

**Comment by Uzay-G** [comment]
Do you mean the package name - like `pip3 install archivy-git`

**Comment by Uzay-G** [comment]
I don't understand what it would do?

**Comment by srevinsaju** [comment]
```bash
archivy plugin add git
archivy plugin remove git
archivy plugin update git
```

**Comment by Uzay-G** [comment]
I'd rather let package organise install instructions, instead of calling pip or something.
