### ISSUE TITLE
Improve tag functionality

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#168]
Currently, tags are very limited - left more as a functionality the user can script around then a feature archivy embodies.

Features to add / think about:

- #119
- tag view to see data with specific tags
- rethink use of tags:
  It could be more interesting to have a structure where you embed the tags in the content like this: `I went to a #computer-science event ...` and this would be tagged `computer-science`.

Any other ideas?

**Comment by cannibalox** [comment]
maybe nested tags / hierarchical tags like: `#code/python` (or `#code.python`) ? 
similar to Bear, Obsidian, DevonThink, Tiddlywiki.

**Comment by sheep94lion** [comment]
Can the tags be changed now?

**Comment by Uzay-G** [comment]
Currently the only way to change tags is directly editing the file (not through archivy). However, #233 will be merged soon and will provide a rework of the tag system such that they can be changed.

Out of curiosity @sheep94lion, I'd like to ask you about the potential changes of #233. We're planning on replacing the tags which are currently stored as metadata, and instead directly embedding tags inside content, like this: `I went to a #python conf` -> here the tag is python. We think this is more effective / intuitive way to make / group content. With this implementation, changing tags here would just mean removing the `#` before python.

How do you feel about this type of tag system?

**Comment by Uzay-G** [comment]
I think the tag system is now good.
