### ISSUE TITLE
Brainstorm webpage archival

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#169]
Could be interesting to think about how pages are archived and the flaws in our approach.

Initiated by https://github.com/archivy/archivy/issues/74#issuecomment-753446569

**Comment by hexylena** [comment]
If it helps, I've really liked WARC in the past for this:

- https://www.loc.gov/preservation/digital/formats/fdd/fdd000236.shtml
- https://github.com/webrecorder/warcio

But they're not super easy to capture unfortunately.

**Comment by clemux** [comment]
I've been using this webextension for saving some webpages: https://github.com/gildas-lormeau/SingleFile

I wonder if it could be easily adapted for uploading the HTML files to archivy.  

Also archivebox has this: https://github.com/tjhorner/archivebox-exporter (MIT license)

Might be even better.

**Comment by Uzay-G** [comment]
#275

**Comment by Uzay-G** [comment]
Closing as other issues address this.
