### ISSUE TITLE
Deal with minified JS.

### ISSUE THREAD

**Issue by srevinsaju** [archivy/archivy#173]
Can we add a bootstrapping command to `archivy init` which would automatically download the latest minified JS to the directory? What do you think?

Moving to another issue.

_Originally posted by @srevinsaju in https://github.com/archivy/archivy/issues/171#issuecomment-753641430_

**Comment by srevinsaju** [comment]
As long as nothing is bundled, we do not have to worry about LICENSING. So, the best way should be to download them on user end. 

We should not use `npm`. `npm` is not supposed to be used in web browsers. On July 4, 2020: I and @diogoscf had a conversation about using `npm` modules in web browser:

```
Srevin: Using <script src="/node_modules/path/to/lib/sth.js"> looks like a hack to call the script
Srevin: I previously used CDN to get the libs; but I feel npm is a easier way of handling deps
:
:
Diogo: Oh you're trying to load node_modules in the browser? That's a big no no
Srevin: oh
Srevin: is it not supposed to be done
Diogo: Node_modules usually includes source codes and readmes and stuff
Diogo: Which you do not want to be loading
Srevin: ohhh
Srevin: ok, i did not know of those
Srevin: So I should stick with CDN right?
Diogo: Yes
Diogo: And load it with a script tag
Srevin: ok thanks a lot
: 
: 
Srevin: I would have wasted my time loading require
Diogo: That wouldn't have worked anyways since require is a node.js thing
Diogo: You can do import but that's a very new feature and will only work in the most recent browsers
Srevin: ohh; ok!
```

Alternative would be, to use `npm` to install all libraries and use webpack, or snowpack to compile it to a minified js

**Comment by Uzay-G** [comment]
I'd rather not have npm as a part of the dev process. Also downloading the files during `archivy init` might not be a good idea and I'd rather not make requests to download files like this on the user end.

What could work is to `curl` the files in the gh action that deploys the package and then they would be saved but that also doesn't really solve anything.

Your problem with the vendoring is licensing?

**Comment by srevinsaju** [comment]
> I'd rather not have npm as a part of the dev process.
Yea, agreed. I am not a fan either.

> Also downloading the files during `archivy init` might not be a good idea and I'd rather not make requests to download files like this on the user end.

Why not? What are the disadvantages?



> What could work is to `curl` the files in the gh action that deploys the package and then they would be saved but that also doesn't really solve anything.

Quite the same.

> 
> Your problem with the vendoring is licensing?

Licensing is one of the problems. `git` is also very bad at tracking minified files.

**Comment by Uzay-G** [comment]
> Why not? What are the disadvantages?

We'd have to explain that we're downloading these js assets because gathering / downloading files onto a user's system is otherwise a bit shady - and I'd rather not do that.

> Quite the same.

No because this way the user has no interaction with the consequences of this problem and all they have to do is install the package. However, I'm not sure if in this case we still suffer from licensing issues if we include the file in the pypi package.

**Comment by srevinsaju** [comment]
> > Why not? What are the disadvantages?
> 
> We'd have to explain that we're downloading these js assets because gathering / downloading files onto a user's system is otherwise a bit shady - and I'd rather not do that.

Yes, we need to explain them. There is nothing wrong. 

I strongly do not suggest a CDN either, as it will matter the privacy.

> 
> > Quite the same.
> 
> No because this way the user has no interaction with the consequences of this problem and all they have to do is install the package. However, I'm not sure if in this case we still suffer from licensing issues if we include the file in the pypi package.

Oh, you mean... adding the minified js or css into the final `.whl`? That makes it no different. As you said, the licensing issue will be there. Perhaps, as a first step:

- [ ] List the third party libraries (not from pypi), bundled in archivy
- [ ] List the licenses of each library

We can then decide what to do.

**Comment by Uzay-G** [comment]
- Katex - MIT
- Highlight.js - BSD-3 Clause license
## Packages for the parser
Most of these are quite small, providing minor functionality
- [markdown-it-texmath](https://github.com/goessner/markdown-it-texmath) - MIT
- https://github.com/markdown-it/markdown-it @license MIT
- https://github.com/markdown-it/markdown-it-footnote MIT
- https://github.com/valeriangalliat/markdown-it-anchor/ unlicense
- https://github.com/nagaozen/markdown-it-toc-done-right MIT
- https://github.com/markdown-it/markdown-it-mark MIT

**Comment by srevinsaju** [comment]
Ah, we should document this somewhere for transparency. Apart from that, on the bright side, most of the third part libs you have chosen is MIT license, which adheres to archivy's license, which is also MIT. As for fixing the licensing, adding plain text of BSD-3 Clause License and Unlicense nearby their respective minified js / css would solve it temporarily.

**Comment by srevinsaju** [comment]
What about third party CSS? Do we use them?

**Comment by srevinsaju** [comment]
Just realized that, there is no need for adding `Unlicense`'s plain text LICENSE, as its compatible with MIT. BSD-3 is the only sad one :thinking:

**Comment by Uzay-G** [comment]
We use one component of the MIT-license https://github.com/primer/css library for styling the markdown rendering.

Otherwise there is a syntax highlighting thing theme css that is part of highlight.js - so also MIT

**Comment by Uzay-G** [comment]
*Sorry it might not be MIT then - but BSD-3

**Comment by srevinsaju** [comment]
ah, so adding [this](https://github.com/highlightjs/highlight.js/blob/master/LICENSE) to your repo should fix the licensing issues

**Comment by Uzay-G** [comment]
Where do you think I should add it?

**Comment by Uzay-G** [comment]
In the file structure.

**Comment by srevinsaju** [comment]
I would say, into https://github.com/archivy/archivy/tree/master/archivy/static

**Comment by Uzay-G** [comment]
Good idea, I put them there :+1:

**Comment by srevinsaju** [comment]
Perfect
