### ISSUE TITLE
Creating subfolders broken

### ISSUE THREAD

**Issue by ygaeon** [archivy/archivy#180]
New install.

- Using the UI to "Create sub directory" `Servers`.
- The "root -> Servers" is displayed on the top and a corresponding folder is created in the USER_DIR folder.
- I continue to create another sub directory `test`.
- Now "root -> Serverstest" is displayed on the top and a corresponding folder "Servertest" is created in the USER_DIR folder.

**Expected result:**
I expected a folder to be created in "root -> Servers -> test" with the corresponding folder "USER_DIR/Servers/test/".

```
$ archivy --version
[2021-01-16 14:52:07,780] INFO in __init__: Elasticsearch index already created
Python 3.7.9
Flask 1.1.2
Werkzeug 1.0.1
```

**Comment by Uzay-G** [comment]
Ok this should be fixed in the commit I just pushed. I'm about to make a new release with the fixes for this and the other issue.
