### ISSUE TITLE
Login not working 

### ISSUE THREAD

**Issue by lrich** [archivy/archivy#181]
Hi

I Installed archivy in a virtual environment with gunicorn and flask

After setting up a service, and nginx, I can see the login page using my URL OK

I set the admin uname and passwword during archivy init, however I can't login

I noticed the db.json file in my /.localshare/archivy directory contains the password I created

This is not the same folder as my virtual environment - do I needed to move this db.json file, or do some other adjustment?

**Comment by Uzay-G** [comment]
What do you mean by virtual environment, a python virtual environment?

**Comment by Uzay-G** [comment]
Like `venv` ? If you tell me what software you used for the virtual environment, I can try and debug the problem :)

**Comment by lrich** [comment]
Hi..Thanks for helping! Here are the steps ...

Using AWS EC2 Ubuntu

- Installed nginx
https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-18-04

sudo apt update
sudo apt install nginx

sudo ufw app list

sudo ufw allow 'Nginx HTTP'

systemctl status nginx


- Flask, Gunicorn and Nginx
https://www.digitalocean.com/community/tutorials/how-to-serve-flask-applications-with-gunicorn-and-nginx-on-ubuntu-18-04

sudo apt update
sudo apt install python3-pip python3-dev build-essential libssl-dev libffi-dev python3-setuptools

sudo apt install python3-venv

mkdir ~/archivyproject
cd ~/archivyproject

python3.8 -m venv archivyprojectenv

source archivyprojectenv/bin/activate

pip install wheel

pip install gunicorn flask

*** Next steps Archivy ****

pip install archivy

archivy init   ---- Here I use all default settings, and do not use elastic search, I set up the admin uname and pasword here as well

sudo ufw allow 5000

archivy run --- Test with curl, Then I Ctrl-C to close


gunicorn --bind 0.0.0.0:5000 archivy:app --- then ctrl-C


deactivate

sudo nano /etc/systemd/system/archivyproject.service

*** here is the text ***


Description=Gunicorn instance to serve myproject
After=network.target

[Service]
User=ubuntu
Group=www-data
WorkingDirectory=/home/ubuntu/archivyproject
Environment="PATH=/home/ubuntu/archivyproject/archivyprojectenv/bin"
ExecStart=/home/ubuntu/archivyproject/archivyprojectenv/bin/gunicorn --workers 3 --bind unix:archivyproject.sock -m 007 archivy:app

[Install]
WantedBy=multi-user.target



*** end of the text ****


sudo systemctl start myproject
sudo systemctl enable myproject

sudo systemctl status myproject


sudo nano /etc/nginx/sites-available/archivyproject


*** nginx text ***


server {
    listen 80;
    server_name ec2-52-14-30-71.us-east-2.compute.amazonaws.com;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/archivyproject/archivyproject.sock;
    }
}




*** end text ***

sudo ln -s /etc/nginx/sites-available/archivyproject /etc/nginx/sites-enabled

sudo nginx -t  

sudo systemctl restart nginx

sudo ufw delete allow 5000
sudo ufw allow 'Nginx Full'



At this point I go to http://ec2-52-14-30-71.us-east-2.compute.amazonaws.com/ and see the login page. 

I enter the credentials set up during archivy init, and nothing happens.


---------------

Some pics .....

Here is the contents of /home/ubuntu/archivyproject/archivyprojectenv/bin/
![archivy3](https://user-images.githubusercontent.com/240381/105508178-127f8c80-5c9a-11eb-8b6b-7ceaae769983.png)


Here is my /home/ubuntu 
![archivy2](https://user-images.githubusercontent.com/240381/105508211-1f03e500-5c9a-11eb-9762-b813f39750ed.png)


Interesting, the db.json file that holds the login credentials is in the  /home/ubuntu/.local/share/archivy folder...
could that have some type of permission issue?
![archivy1](https://user-images.githubusercontent.com/240381/105508264-2dea9780-5c9a-11eb-9757-fbf0c1733cd7.png)

**Comment by srevinsaju** [comment]
@lrich 

can you try
```nginx


server {
  listen 80;
  server_name ec2-52-14-30-71.us-east-2.compute.amazonaws.com;
  location / {
      proxy_pass http://localhost:5000;
  }
}


```

**Comment by srevinsaju** [comment]
I have got archivy working with the following steps, if followed properly, you are likely to get archivy working


```bash
# run archivy as a dedicated user
sudo useradd -r -m archivy
sudo su - archivy


virtualenv archivy
source archivy/bin/activate
pip3 install archivy gunicorn

# test archivy
archivy --version
```

```bash
$ archivy init
This is the archivy installation initialization wizard.
Enter the full path of the directory where you'd like us to store data. [/home/archivy]: /home/archivy/data
Would you like to enable Elasticsearch? For this to work when you run archivy, you must have ES installed.See https://archivy.github.io/setup-search/ for more info. [y/N]: N
Would you like to create a new admin user? [y/N]: y
Username: ****     
Password: 
Repeat for confirmation: 
User root successfully created.
Host [localhost (127.0.0.1)]: 
Config successfully created at /home/archivy/.local/share/archivy/config.yml
```

```bash
# test archivy working
archivy run 

# Ctrl + C
# Ctrl + D, exit archivy user
```

Now make changes to nginx configuration, add this to your nginx configuration
```nginx
server {
        listen 80;
        listen [::]:80;
        keepalive_timeout   70;
        server_name yourdomain.example.org;
        location / {
                proxy_pass      http://127.0.0.1:5000;
        }
}
```

```bash
sudo nginx -t

sudo systemctl restart nginx
```

Now, login as archivy user again 
```bash
sudo su - archivy
source archivy/bin/activate
archivy run
```
Navigate to your domain on a browser
Verify that archivy is up, and can be logged in successfully.

If you reached so far, let me know.


If using this recipe elsewhere, please remember to attribute me.

**Comment by Uzay-G** [comment]
Did this work for you @lrich ?

**Comment by lrich** [comment]
Hi

Tried the code and still no go. Unfortunately, I have to put this all on hold for other projects, may get back to it later and try again.

Thanks for your help!
