### ISSUE TITLE
Think about cross-platform in Archivy -> Ways to allow access to Archivy from any device.

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#19]

**Comment by HarshaVardhanJ** [comment]
Is it not accessible by any device in its current state? The frontend runs in a browser, so any device should be able to access it. Could you clarify what you mean?

**Comment by Uzay-G** [comment]
The frontend can be accessed but the problem is that once can only edit data from the system where the server is hosted itself because there is no ui for editing.

**Comment by clemux** [comment]
As a temporary workaround, I would suggest disabling running external programs on the server though an environment variable.

**Comment by clemux** [comment]
Also, the API I started in #63 could be extended with an endpoint for retrieving and uploading notes. A flask cli command could be used to do something like:
```
$ edit-note 23 # GET , xdg-open /tmp/23.md, PUT 
```

**Comment by Uzay-G** [comment]
Linked to https://github.com/Uzay-G/archivy/issues/66 as a login system for users to access archivy remotely and https://github.com/Uzay-G/archivy/issues/33.

**Comment by Uzay-G** [comment]
#137 contributes immensely to this, and #131 will be the final step.
