### ISSUE TITLE
create subfolder not working

### ISSUE THREAD

**Issue by mike741** [archivy/archivy#190]
Environment: running on windows 10, fresh installation of archivy & python, logged in as admin

Issue: Creating subfolders "randomly" stops working. After quickly creating a few folders, all of which showed "created successful" message, only a portion were actually visible. In the server console I see the following error, I am not sure if its related as it doesn't show up every time:

> 
> 127.0.0.1 - - [02/Feb/2021 17:42:22] "←[37mGET /?path= HTTP/1.1←[0m" 200 -
> [2021-02-02 17:42:27,523] ERROR in app: Exception on / [GET]
> Traceback (most recent call last):
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 2447, in wsgi_app
>     response = self.full_dispatch_request()
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\_compat.py", line 39, in reraise
>     raise value
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\flask\app.py", line 1936, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\archivy\routes.py", line 40, in index
>     files = data.get_items(path=path)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\archivy\data.py", line 68, in get_items
>     data = frontmatter.load(filepath)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\site-packages\frontmatter\__init__.py", line 152, in load
>     text = f.read()
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\codecs.py", line 701, in read
>     return self.reader.read(size)
>   File "c:\users\mike\appdata\local\programs\python\python39\lib\codecs.py", line 504, in read
>     newchars, decodedbytes = self.decode(data, self.errors)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa9 in position 2710: invalid start byte

[SOLVED] the error is actually that empty folders are invisible until something is put into them, so when a directory is created, and then its parent directory is visited, the newly created sub directory is still invisible.

**Comment by Uzay-G** [comment]
Hmm this isn't the correct behaviour, I'll fix this so the directory appears :)

**Comment by Uzay-G** [comment]
Ok just fixed this in https://github.com/archivy/archivy/commit/0bb3294a3125d591c71e33ba51c6e6039cfe1a50. Will be in the next release :)
