### ISSUE TITLE
Please implement way to rename folders and notes

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#191]
Not 10 minutes in, and I already wanted to change a folder name that contains notes already.
Renaming of folders and notes would be ideal. It would be great if Archivy allowed you to do this at some stage in the future.

Will things break if I rename the folder on disk and restart archivy?

**Comment by Uzay-G** [comment]
Nothing bad will happen if you rename folders or note titles on disk, but yeah this should def be implemented :thinking:

**Comment by Uzay-G** [comment]
I'll put this as high priority :)

**Comment by Uzay-G** [comment]
Alright, renaming the note is possible in v1.3.0 :tada:

Revisiting this issue, you're right, we have to implement this for folders too!

**Comment by Uzay-G** [comment]
#248

**Comment by Uzay-G** [comment]
Fixed in #248 !
