### ISSUE TITLE
Request: Implement logout method

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#193]
If I use Archivy from a shared computer I'll probably want to log out afterwards so others can't see/edit my notes, I can't see a way to do this at the moment?

**Comment by Uzay-G** [comment]
What do you think of something like this:

![image](https://user-images.githubusercontent.com/52892257/107434107-95259a00-6b2a-11eb-8216-1e540ce901ae.png)

(On the profile page)

**Comment by BrianGilbert** [comment]
I'd personally suggest making it the same size as the submit button and right aligned to the inputs beside submit

**Comment by Uzay-G** [comment]
Oh good idea, it's in the latest release (v1.0.1) :)
