### ISSUE TITLE
Sort folder tree alphabetically

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#194]
![Home - Archivy 2021-02-03 16-44-12](https://user-images.githubusercontent.com/114017/106703806-17035800-663f-11eb-9a19-b79845080566.png)

As I add more and more folders and subfolders, finding them will become very difficult without some form of logical sorting in the tree, I see they are Alphabetical in the main area of the page and posit this may make sense in the tree as well?

**Comment by Uzay-G** [comment]
Good idea, I planned to do this but just forgot! Fixed in https://github.com/archivy/archivy/commit/fa1d9588d1e0925cfdb02b837f187bd1ffa1b565 and will be in the next release :)
