### ISSUE TITLE
ADD: Static site generation of knowledge base data into a public, static website.

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#2]
I think this could be useful for those who want to share their knowledge bases and publish them.

The program would simply generate static html files based on the data of the knowledge base.

**Comment by Uzay-G** [comment]
Do other people also think this is a useful feature?

**Comment by clemux** [comment]
I could see the value if archivy supported annotations (highlighting, comments), but I can't see the use-case for now, could you elaborate?

**Comment by Uzay-G** [comment]
It would be to serve your notes and other stuff as a public wiki other people could access. Like a blog, except instead it would be a public wiki of your notes, bookmarks, etc...

**Comment by Uzay-G** [comment]
This can and will be focused on as a plugin, not as part of the source, so I'll close the issue for now.
