### ISSUE TITLE
[Feature request] support for richer .md content tags / scripts etc.

### ISSUE THREAD

**Issue by ventusff** [archivy/archivy#203]
See this example page: https://ventusff.github.io/blog/2021/showcase/

Some requirements included I can think of:
- support html tags: `<u>`, `<br>`, `<details>`, `<summary>` etc.
- inline maths 
  - automaticly decide whether inline or display math when using the same `$$...$$` deliminator ?
- support `mermaid` flowchart rendering. (this I think could be implemented as a plugin, since it's not popularly needed)

The `.md` file in the above example page is perfectly viewed via both `jekyll` rendered `.html` page and `typora` editor, but currently not correctly rendered in `archivy`.

**Comment by ventusff** [comment]
How are the `.md` files being rendered in `archivy`? 
I think maybe `archivy` could use some common `.md` renderer, like `kramdown`.
Or, maybe some plugins could be developed for choosing different `.md` renderers, like in `vscode`.

**Comment by Uzay-G** [comment]
Archivy uses the [markdown-it](https://github.com/markdown-it/markdown-it) parser. It works with a system of plugins for new functinality, we could add some if people find them useful.

I don't understand what you mean for math, Archivy already supports inline KaTeX rendering.

However I think generally being able to script in additional parsing (on a user side, with plugins for example), would be very cool.

**Comment by ventusff** [comment]
Hi, thanks for the information! 
Sorry I didn't do much code digging into the repo before, but now I see where the renderer and math is defined.

Generally, I think many editor and renderer configs which are hard-coded now could be added to the config file.

### As for inline math:

What I mean is adding an easy-to-use config to change the `delimiters` option here
https://github.com/archivy/archivy/blob/57ca3b82c85cd348b384de333ac75135fdb4d272/archivy/templates/markdown-parser.html#L26
from `dollars` to `kramdown`. 

Since I already have tons of markdown files all following the `krandown` delimiters and wanting to transfer them into `archivy` seamlessly, it is a little cumbersome and sometimes buggy to reformat the markdown files themselves.

Currently I can change it here manually in the cloned repo and reinstall `archivy` with `pip install .`, but a simple config would be nicer.

There are also many other `delimiters` choices, as listed [[here, in markdown-it repo]](https://github.com/goessner/markdown-it-texmath#features). I believe there will be some users which are like me that already have many markdown files defined following different `delimiters`, so yeah again a config would have been great :)

### As for math renderers:

`KaTex` is cool, but what do you think of adding options to switch to `mathjax.js` ? `mathjax` has some nice features, like copying original Tex command with a simple right-click.

### As for addtional parsing

Good to hear! Looking forward to some nice pluggins. `archivy` is a great tool with great potentials.

**Comment by Uzay-G** [comment]
Hmm I see what you mean. I think we need to find a way to allow the user to be able to add the plugins they want to use **and** also customize the parser, but I'm not sure how we should structure this. If you have any ideas please check out the new issue at #209

**Comment by Uzay-G** [comment]
Is there still interest for this? I could build a system to allow easy add on of plugins in the config. Ping the thread if so.

**Comment by Uzay-G** [comment]
See https://archivy.github.io/config/#editor-configuration for more info on how to do many of these things asked for here. Closing for now.
