### ISSUE TITLE
Request: Add the option of formatting with utf-8

### ISSUE THREAD

**Issue by AikenH** [archivy/archivy#204]
When I try to format the local `md`, the following error message appears:

- `'gbk' codec can't decode byte 0x9a in position 118: illegal multibyte sequence` ;

According to my knowledge, it looks like  the file is opened in text mode with a "gbk" encoding. 
Some Unicode characters that can't be represented in “gbk”.

> “1. encode with 'gbk' but use the 'replace' option
>  2.  encode with 'gbk' but use the 'ignore' option
>  3. encode with an encoding that supports ALL Unicode characters (utf-8, gb18030) and for which you have a display mechanism that renders all those characters that aren't in gbk”

[John Machin_ StackOverlow](https://stackoverflow.com/questions/3218014/unicodeencodeerror-gbk-codec-cant-encode-character-illegal-multibyte-sequen)

**Comment by Uzay-G** [comment]
This should be fixed in the v1.0.1 release, thanks for bringing it up !
