### ISSUE TITLE
Is it possible to point archivy to existing directory of markdown files?

### ISSUE THREAD

**Issue by nicolae-stroncea** [archivy/archivy#207]
Does archivy allow for pointing the folder towards an existing folder structure? Ideally I want to just point it to my existing folder which has markdown files(and other file types) so that it starts displaying files from there and so that if I add a new file it will add it in my original directory.

What I've currently seen is that if I point it to a folder, it will generate a data/ folder inside where it will read the data from instead.

**Comment by nicolae-stroncea** [comment]
So I tried this by pointing archivy to my folder, and moving everything into a data/ subfolder. Archivy correctly read the folder structure, and I can see it now in the sidebar, however I cannot open any markdown file since I get the error:
`jinja2.exceptions.UndefinedError: 'frontmatter.Post object' has no attribute 'title'`
which is probably because my markdown files don't have the frontmatter

**Comment by Uzay-G** [comment]
You can use the `archivy format` command to add all the frontmatter to the markdown files you have (including setting `title` by default to the filename)
