### ISSUE TITLE
Filename too long error

### ISSUE THREAD

**Issue by a10software** [archivy/archivy#211]
Hi there, 

I've just set up archivy via Docker on a Linux machine and I'm getting a filename too long error when I try to save this very github repo. My theory is that archivy is pulling the `about` metadata from the URI. My recommendation is that archivy pull the URI stub itself (github.com.archivy or something to that effect) in cases where the filename would be way too long.

Add Link: https://github.com/archivy/archivy

```
OSError: [Errno 36] Filename too long: '/archivy/data/data/52-GitHub_-_archivy_archivy_Archivy_is_a_self-hosted_knowledge_repository_that_allows_you_to_safely_preserve_useful_content_that_contributes_to_your_own_personal_searchable_and_extendable_wiki.md' | stderr
```

**Comment by Uzay-G** [comment]
Hmm I'm not sure what the upper limit for this should be :thinking:

**Comment by a10software** [comment]
There might be a way to handle the filename too long exception and try a more truncated filename? Or maybe just cap it at 255 chars which seems to the limit for several OSes out there (generally it's 255 chars or bytes). However, pathname is another challenge. Source: https://serverfault.com/questions/9546/filename-length-limits-on-linux#9548

Oddly enough, that may not solve the problem for myself since the error I posted shows a 214 char-long pathname. I'm on BTRFS though.

**Comment by Uzay-G** [comment]
Sorry for fixing this late, but I pushed a patch and it'll be in the next release :)
