### ISSUE TITLE
403 Forbidden for certain links

### ISSUE THREAD

**Issue by a10software** [archivy/archivy#212]
The web scraper is getting a 403 response when trying to bookmark certain links. Examples: 
https://zenhabits.net/free/
https://sloanreview.mit.edu/article/yes-im-feeling-bad-about-climate-change-lets-discuss/

**Comment by Uzay-G** [comment]
Thanks for finding this, it seems a "Forbidden" response is being returned because we didn't specify a user-agent when we made the request. I'm going to push a fix !

**Comment by Uzay-G** [comment]
Ok I just fixed this in https://github.com/archivy/archivy/commit/6a943b35cc1ebfd674a2168ec40e00d66344fbec. It'll be in the next release :) and thanks again for bringing it up :+1:
