### ISSUE TITLE
Thoughts on switching to pipenv?

### ISSUE THREAD

**Issue by FlipEnergy** [archivy/archivy#214]
I see you guys use straight up requirements.txt
This is fine for the docs but for development, CI and releasing, I think it's be nice to switch to pipenv. I'm happy to make a PR to help with this. 

I'm raising this issue because it wasn't even obvious what version of python you guys are working on for Archivy. The black workflow runs python 3.8 but the other ones run python 3.7.

EDIT: `FROM python:3.9-alpine` okay found my answer. Yeah not a huge deal but may be wise to streamline it all to python 3.8.

**Comment by Uzay-G** [comment]
What do you think about this @srevinsaju ?

**Comment by FlipEnergy** [comment]
Hey. I opened this on a whim and since this isn't really an issue I'm gonna close this. Don't feel like you need to continue the discussion,

**Comment by srevinsaju** [comment]
I have been personally been using `Pipenv` for testing archivy, and now am moving other projects to `pipenv` instead of the old `pip`. This is safer and helps to keep the dependencies in their own virtual environments.

**Comment by srevinsaju** [comment]
I just committed my `Pipfile` and `Pipfile.lock` which I had been using for archivy in #216 , in case if it would be useful. 

All you need to do is

```bash
pipenv sync && pipenv lock
pipenv shell

python3 -m archivy.cli run 

```
