### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by edditler** [archivy/archivy#228]
This refers to https://github.com/archivy/archivy/issues/89 also.

I think it would be nice to be able to chose between themes or at least be able to supply some custom CSS. I'm wondering what you are thinking. Should there be a `./themes` folder next to `./data` and `./images` so that everyone can add/adapt easily for themselves or rather a set of official themes?

One could store the name of the theme in `config.yml` and then include the right css at https://github.com/archivy/archivy/blob/master/archivy/templates/base.html#L6.

---

Alternatively there could also be some additional CSS file that's always loaded (`./custom.css` or something). Some use cases:

- For me `width: 22%` ist not enough for the sidebar
- One could apply something like 
```css
.table-of-contents {
  position: fixed;
  right: 1em;
}
```
-   ...

**Comment by Uzay-G** [comment]
Hmm interesting.

Maybe archivy users could have a `styling/` directory, and all css files in there would get bundled together and then served with the instance?

That way, to reuse someone's themes you would just have to copy their files in, and making your own custom little change would be as simple as adding a `custom.css`

**Comment by edditler** [comment]
So in that case `archivy init` would create the folder `./styling` and put the `main.css` in there?

**Comment by Uzay-G** [comment]
Fixed in #235
