### ISSUE TITLE
Editor font should be monospaced

### ISSUE THREAD

**Issue by edditler** [archivy/archivy#232]
In the demo of markdown-it at https://markdown-it.github.io the editor font-family is `Menlo, Monaco, Consolas, "Courier New", monospace`. In archivy this is not the case for some reason.

**Comment by Uzay-G** [comment]
Why do you think it would be better monospaced? This is really just a matter of preference that could also be fixed with #228

**Comment by edditler** [comment]
for me it's stuff like 

---
'''
this code does awesome things:

'''python
def code():
    indents-are-important()
'''

'''

the code at least should be monospaced so that it can be read nicely.

**Comment by Uzay-G** [comment]
Yeah I see what you mean. I'll close this for now because once we have #228 implemented it'll just be a matter of adding a line of css, so that will fix this :)
