### ISSUE TITLE
Allow override of "Archivy" for site title and page headings

### ISSUE THREAD

**Issue by ropable** [archivy/archivy#238]
It would be useful to allow a user to override the default value of "Archivy" for page title and heading values with their own value, e.g. "My awesome Archivy". This should be relatively trivial to include as a configuration variable, injecting something like SITE_TITLE on the base template.

**Comment by ropable** [comment]
I prototyped a few changes that should allow this; these are reviewable at this commit: https://github.com/ropable/archivy/commit/463c481bb5505cf9ee2c04c1c83b67d777604887

I won't submit a PR or do anything further with it prior to discussion here.

**Comment by Uzay-G** [comment]
That's a good idea! You can open a PR and then I'll review it / help out if there are any problems :)

**Comment by ropable** [comment]
Thanks! PR #239 refers. Apologies if my overzealous culling of leading/trailing spaces increased the number of files in the PR.
