### ISSUE TITLE
Display Archivy version somewhere within it's UI

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#240]
I like to keep Archivy up to date, but that means I have to log into the server to confirm what version I am running, can we please get the version displayed in the web interface to make it easier?

**Comment by Uzay-G** [comment]
Yeah we could do that.
Where do you think it would fit best?

**Comment by BrianGilbert** [comment]
I think this look ok?

![root - Archivy 2021-06-22 10-30-52](https://user-images.githubusercontent.com/114017/122844470-14cb3d00-d345-11eb-811d-8a0529134e55.png)


```
<div class="Header-item full">
  <a class="Header-link" href="/">
    <img src="https://archivy.github.io/img/logo-2.png" alt="archivy logo" width="35" height="35">
    <h3>Archivy</h3>
  </a>
  <p>&nbsp;v1.3.0</p>
</div>
```

**Comment by Uzay-G** [comment]
Hmm yeah that looks good, I just implemented it in the last commit! Thanks for the suggestion :blush:
