### ISSUE TITLE
How can I extend editor configuration?

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#247]
I'd like to add a few editor icons to the toolbar if possible?

Related: https://github.com/archivy/archivy-docker/issues/13

**Comment by Uzay-G** [comment]
Hi! I'm currently traveling, but I'll implement a new config option for this to be possible.

Out of curiosity, what option specifically would you like to add in your config?

**Comment by BrianGilbert** [comment]
I'd definitely be adding list items, so that I can turn multiple lines of text into a list, not sure about others atm.

**Comment by Uzay-G** [comment]
Archivy currently uses an editor called EasyMDE. They offer these default icons, of which Archivy selects some default ones: https://github.com/Ionaru/easy-markdown-editor#toolbar-icons. What we could add is a config option to add some of these icons to the editor.

Is this what you want or do you want direct ability to write code for the editor?

**Comment by BrianGilbert** [comment]
@Uzay-G yes, I was after ability to configure what icons are available please.

**Comment by Uzay-G** [comment]
Alright, I implemented this in https://github.com/archivy/archivy/commit/e081760d530eeecb59bec5a417fa6d11c4cb8be8, will be good in the next release. [Docs](https://archivy.github.io/config/#editor-configuration)

**Comment by Uzay-G** [comment]
Released in 1.7.3
