### ISSUE TITLE
[Question] Upload firefox archive

### ISSUE THREAD

**Issue by makefu** [archivy/archivy#266]
Hi, right now i have all my bookmarks in firefox and i would like to add them to archivy. The archive itself contains ~10k bookmarks, is there any way to upload the whole archive as a batch or via a script?

**Comment by Uzay-G** [comment]
This would be pretty simple with a plugin (https://archivy.github.io/plugins/), that would parse a `bookmarks.json` file and upload them to Archivy.

This would be useful for me too, so I can probably do it soon.

**Comment by makefu** [comment]
Hey @Uzay-G that sounds great, thanks for the heads-up!

**Comment by Uzay-G** [comment]
@makefu this should work: https://github.com/archivy/archivy-firefox.

Tell me how it goes!
Warning, it might take some time for 10k bookmarks.

**Comment by Uzay-G** [comment]
@0x4A6F you upvoted this too, pinging you in case you're interested.
