### ISSUE TITLE
Add a parameter to override the config path for init

### ISSUE THREAD

**Issue by Christoph-Wagner** [archivy/archivy#270]
Currently, `sudo -u archivy archivy init` results in `PermissionError: [Errno 13] Permission denied: '/home/archivy'` which makes sense, as `archivy` is my service user only created for the purpose of running archivy and has no home directory or shell.

Now I fixed that by simply creating the directory, but it seems I should just be able to tell the `init` function where to save the config (and then run archivy with the custom config, though I could just set the appropriate `XDG_CONFIG_HOME` variables inside the systemd service).

**Comment by Uzay-G** [comment]
The problem here is that the config stores the paths where your data is,  so if we did this you'd need to have some argument on the cli to pass a config directory whenever you run archivy. I'm not sure what a good solution to this is.

**Comment by clemux** [comment]
I think an environment variable would be best, if setting `XDG_CONFIG_HOME` in the systemd unit file works, maybe a `ARCHIVY_CONFIG_PATH` variable would be useful for such usecases?

**Comment by Uzay-G** [comment]
Yeah that would work well.

**Comment by clemux** [comment]
Would be this satisfactory? https://github.com/archivy/archivy/pull/274

**Comment by Uzay-G** [comment]
Implemented in #274, thanks @clemux. I'll put something about this on the doc website at the next release.
