### ISSUE TITLE
search with ripgrep doesn't work on Windows

### ISSUE THREAD

**Issue by graphixillusion** [archivy/archivy#271]
Hi there. As the titles says, the search isn't working on Windows using ripgrep as backend. I can see this message in the log:

```
ValueError: invalid literal for int() with base 10: 'C:\\Archivy\\data\\UEFI\\1'
127.0.0.1 - - [16/Dec/2021 15:57:16] "←[35m←[1mGET /api/search?query=shell HTTP/1.1←[0m" 500 -
```

I've also tried to ripgrep manually the markdown file inside the data folder and i have no problem at all.

**Comment by Uzay-G** [comment]
Oh oops, I run it on linux and hadn't noticed this! Pushing a fix right now.

**Comment by Uzay-G** [comment]
Alright, I patched a new version. Could you run `pip install archivy==1.6.1` and try again? Thanks for letting me know!

**Comment by graphixillusion** [comment]
@Uzay-G Thank you very much for the super fast fix! Now it's working as intended!
