### ISSUE TITLE
Webextension for saving pages and sending them to archivy

### ISSUE THREAD

**Issue by clemux** [archivy/archivy#276]
I've been using this webextension for saving some webpages: https://github.com/gildas-lormeau/SingleFile

I wonder if it could be easily adapted for uploading the HTML files to archivy.  

Also archivebox has this: https://github.com/tjhorner/archivebox-exporter (MIT license)

Might be even better.

_Originally posted by @clemux in https://github.com/archivy/archivy/issues/169#issuecomment-1003560549_

**Comment by Uzay-G** [comment]
Implemented in recent commits, will be in the next release
