### ISSUE TITLE
deploy within an intranet?

### ISSUE THREAD

**Issue by andrewchenshx** [archivy/archivy#280]
is it possible to deploy archivy within an intranet?
i can install archivy on a server within an intranet, while the client machines can NOT access the public network for some css/icon files or so, so the page does NOT display properly.

**Comment by Uzay-G** [comment]
Ah, that's a good point. I'll try to change is so that those files come packaged with Archivy.

**Comment by Uzay-G** [comment]
Other than the logo, are there any especially annoying things that wouldn't load for you? There's also the LaTeX math stylesheets that are loaded off a CDN.

**Comment by Uzay-G** [comment]
Should be fixed on the next release with https://github.com/archivy/archivy/commit/419668d39cb9dcadb39ba76562a2d88c48bf6038
