### ISSUE TITLE
Request to change the bind address to `0.0.0.0` instead of the default `localhost`.

### ISSUE THREAD

**Issue by HarshaVardhanJ** [archivy/archivy#29]
Currently,`archivy/run.py` is:
```python
from dotenv import load_dotenv

from archivy import app


def main():
    load_dotenv()
    app.run()
```

Could we change it to the following?
```python
...
def main():
  load_dotenv()
  app.run(host='0.0.0.0')
```

When running inside a container, if Flask accepts connections only from `localhost`, I cannot access the server from outside the container. The process will need to listen on *all* interfaces *inside* the container. Can we make this change?

**Comment by HarshaVardhanJ** [comment]
@Uzay-G Also, could you update the changes to the `0.0.5` release?

**Comment by Uzay-G** [comment]
Yes. Ill do it tonight for 0.0.6
