### ISSUE TITLE
Bookmarklet fails: Method Not Allowed  The method is not allowed for the requested URL.

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#291]
I've just updated Archivy to 1.7.2, and recreated my bookmarklet, when I try to use it on any site I get error:

Example

Browse to: https://www.athlegan.com/starting-strength
Use bookmarklet: new window opened at my Archivy instance, required me to authenticate with Archivy, click submit on login form get white screen with following error:
```
Method Not Allowed

The method is not allowed for the requested URL.
```

URL of error page is https://mayarchivydomain.com/save_from_bookmarklet

**Comment by BrianGilbert** [comment]
Incidentally, if I try to add bookmark of this website the images do not get downloaded (configured for download in my Archivy settings)  https://www.athlegan.com/starting-strength

**Comment by Uzay-G** [comment]
@BrianGilbert do the images show though? or are they not even in the saved content?

About the issue you brought up, that's because it goes directly from not logged in to logged in and then redirects to the save link page, which is a POST normally.

I'll try to see what I can do about that, but because of security stuff you might just have to be logged in before saving the article.
Not sure what the best way to implement this is.

**Comment by BrianGilbert** [comment]
> @BrianGilbert do the images show though? or are they not even in the saved content?
> 
> About the issue you brought up, that's because it goes directly from not logged in to logged in and then redirects to the save link page, which is a POST normally.
> 
> I'll try to see what I can do about that, but because of security stuff you might just have to be logged in before saving the article. Not sure what the best way to implement this is.

@Uzay-G so yeah, I was already logged in in another tab, I can make a video if you like?

**Comment by Uzay-G** [comment]
that would be helpful. Thank you!

**Comment by BrianGilbert** [comment]
@Uzay-G https://www.youtube.com/watch?v=0x5NuM2Eoeo

**Comment by Uzay-G** [comment]
Hmm that's really weird. And you're using a normal browser setup right? Like cookies carry over between tabs / both tabs there were in the same session.

Hmm I'll try to see how I can figure this out.

**Comment by BrianGilbert** [comment]
I just tested the bookmarklet in Safari and it did import the page, meaning it must be something about my FF setup, however there is broken HTML in the imported page due to picture tag on images.

**Comment by BrianGilbert** [comment]
Here are all my FF extensions that are enabled:
![Add-ons Manager 2022-03-25 09-43-56](https://user-images.githubusercontent.com/114017/160022240-cc30c3e2-7cb8-4b53-81fa-ff0687cb5139.png)

![Add-ons Manager 2022-03-25 09-44-20](https://user-images.githubusercontent.com/114017/160022261-3c538262-190b-4690-af02-bd1ca1592445.png)

![Add-ons Manager 2022-03-25 09-44-34](https://user-images.githubusercontent.com/114017/160022293-7f1300c9-e1a1-4225-be5b-945342964738.png)

**Comment by Uzay-G** [comment]
Not sure but is it possible the temporary container thing means the new tab doesn't have archivy logged in? I'm trying to replicate this but when I'm logged in it just directly saves the bookmark...

**Comment by BrianGilbert** [comment]
Weirdly this issue only seems to occur when the tabs are in my personal container, when I test in my work container it imports the page correctly, I'd say this is probably closeable and I'll just need to figure out the cause in my local setup.

**Comment by BrianGilbert** [comment]
@Uzay-G I did actually resolve it.. it was related to a setting I had in Sideberry to move default items in personal container, removed that and deleted personal container and it's working as expected now
