### ISSUE TITLE
No apparent way to add tags after page creation?

### ISSUE THREAD

**Issue by BrianGilbert** [archivy/archivy#294]
Hey @Uzay-G I was creating some notes today and noticed that I'm offered the opportunity to add tags when creating a new note, but there doesn't appear to be any way to edit an existing note to add tags?

**Comment by Uzay-G** [comment]
Hey, so basically you can just do this:

![random](https://user-images.githubusercontent.com/52892257/193442524-b9b83737-9928-4f02-8dec-0a28b3bfed8c.gif)
