### ISSUE TITLE
Major performance issues with 450 markdown notes (~200mb data)

### ISSUE THREAD

**Issue by T0BiD** [archivy/archivy#304]
I set up archivy and played around for a bit and it seem like exactly what I was looking for.   
Then I started to put in some (or a lot, depending on the definition) content. Markdown only.   

I currently have around 450 notes, totally around 200mb of data.

The "notes" aren't small. I'd say on average a few thousand lines of text.   

Anyhow, the performance has degraded massively.
Every single action, from navigating to a folder, opening a note or even creating a new one takes between 5 and 10 seconds.
This is borderline unusable.

Funnily enough, the search is still extremely fast, even searching for words occurring thousands of times (like "the") takes less than a second. I guess I have to thank elasticsearch for that.

I'm running archivy in the docker container on a linux machine with 32GB RAM (> 10GB available at all times), NVMe SSD and a Ryzen 7 4700U.   
So I guess the hardware is not the problem.   

Is there anything I can do to increase the performance?

**Comment by T0BiD** [comment]
Edit:
Just checked with `docker stats` and when idling it takes 0% CPU and ~1-2 GiB of RAM.
But whenever I do any action the CPU usage jumps to 99% and RAM increases by at least 2 GiB, sometimes it decreases again to a few hundred MB, sometimes it doesn't.

**Comment by Uzay-G** [comment]
Hey, I think I know what this is due to. I'm going to fix this soon and make a new release. Sorry about that, and I hope you keep using archivy.

**Comment by Uzay-G** [comment]
Hey, can you try the v1.7.5 version and let me know if it's better? Should fix the problem.

**Comment by T0BiD** [comment]
Way better, thanks a lot for the quick fix!
