### ISSUE TITLE
Need a logo for archivy

### ISSUE THREAD

**Issue by srevinsaju** [archivy/archivy#32]
(Maybe this issue can be marked as a `good-first-issue`)

**Comment by cktang88** [comment]
@Uzay-G do you have logos that you want archivy's to have a similar feel/look to? I've personally found going to https://logomaster.ai/ and seeing a few options helpful in narrowing down logo options before iterating.

**Comment by RushiVachhani** [comment]
I would like to take it up, if you don't mind.

**Comment by srevinsaju** [comment]
@RushiVachhani would you like to show some iterations of what is your idea on archivy's logo?

**Comment by royquilor** [comment]
Hi, please could you provide 3 keywords that represent the brand or the main target audience? Or shall I share some concepts?

**Comment by srevinsaju** [comment]
@royquilor we would be glad to hear your idea about archivy :smile:

**Comment by Uzay-G** [comment]
@royquilor Some keywords would be "knowledge", "archive", and the more visual idea of a "digital garden" for your thoughts

**Comment by srevinsaju** [comment]
I like the idea of "digita garden" :tada:

**Comment by Uzay-G** [comment]
![archivy](https://user-images.githubusercontent.com/52892257/96354339-e7533300-10d5-11eb-8777-f264098c6d74.png)

This is something I was working on today. I might improve it and we could use this.

Thoughts?

**Comment by royquilor** [comment]
Hi all, here are some ideas. I used a simple leaf shape with a circle like a branch to represent a lowercase a. On version 2, I flipped the leaf to see how it looks vertically, but the letter - a not as obvious. 

Concept A: leaf + a + branch circle
![concept-a](https://user-images.githubusercontent.com/2366186/96491440-29958500-123a-11eb-8b19-20a412d0ab4d.png)
![concept-a-green](https://user-images.githubusercontent.com/2366186/96491460-3023fc80-123a-11eb-9935-9ab2a560d38a.png)

Concept B: leaf + a + branch circle and square for simple digital pixel look
![concept-b](https://user-images.githubusercontent.com/2366186/96491566-52b61580-123a-11eb-8017-1bc16ba9f55d.png)
![concept-b-green](https://user-images.githubusercontent.com/2366186/96491579-577ac980-123a-11eb-95b2-bdcb6ea0bbba.png)

I look forward to your feedback. The leaf shape could put changed to a speech or chat bubble like above for exploration.

**Comment by srevinsaju** [comment]
Looks really professional!!!! @royquilor you are amazing!

**Comment by srevinsaju** [comment]
I vote for this: 
![image](https://user-images.githubusercontent.com/48695438/96496008-57d28f00-1251-11eb-89b3-fc67ba1c9173.png)


:tada:

**Comment by srevinsaju** [comment]
@royquilor which is the font you have used, in `archivy`, is it an open source font? if yes, can you provide the name of the font. :smile:

**Comment by royquilor** [comment]
@srevinsaju thanks for the nice feedback. The type is indeed open source:
https://fonts.floriankarsten.com/space-grotesk and the original is Space Mono (Colophon Foundry) which is also free on google fonts. I love both of them :)

**Comment by Uzay-G** [comment]
Very nice! I agree with srevin that that one is nice! Could you maybe send me a png with a) just the logo without the text and b) the asset of the png srevin sent.

Thank you so much for your great work :+1:

**Comment by srevinsaju** [comment]
Along with that, I guess @Uzay-G would agree with me, you could please provide the license you would like to provide the artwork to us, i.e (CC-BY-SA 4.0, CC-BY-SA-ND 4.0, CC-BY-NC-ND 4.0, Unlicense, etc), I see you have done a lot of interesting work, so you would know, so you get the rights / copyright of the cool artwork you just created, for archivy, open source :tada: 

We would be glad to see you submitting this logo to the Archivy repository, yourself, best, as an SVG document + the PNG as @Uzay-G suggested :tada: . @Uzay-G could add on... :rocket:

**Comment by HarshaVardhanJ** [comment]
@royquilor This looks great!

**Comment by Uzay-G** [comment]
@royquilor could you please send us a png of the thing you sent earlier? It would help us go forward even if you haven't decided on a license yet. We can help you more with that on the discord server.

**Comment by royquilor** [comment]
Hi all, sorry took a while. Here are the png
![logo-icon](https://user-images.githubusercontent.com/2366186/97121884-8355ed80-1719-11eb-8c6e-801eede2d698.png)
![logo-text-lg](https://user-images.githubusercontent.com/2366186/97121885-84871a80-1719-11eb-89d9-c9c53434f755.png)
![logo-text-md](https://user-images.githubusercontent.com/2366186/97121886-84871a80-1719-11eb-9a99-4fbfda8b9869.png)
![logo-text-sm](https://user-images.githubusercontent.com/2366186/97121887-851fb100-1719-11eb-84f0-de0c00119442.png)
![logo-text-xs](https://user-images.githubusercontent.com/2366186/97121888-851fb100-1719-11eb-8edb-971c684b6378.png)
Color is #48BB78
Will also work with plain black and white with the correct contrasting background.
Will make a pr early this week with the SVG.

**Comment by srevinsaju** [comment]
@royquilor a cool tool by creative commons to help decide your license : https://chooser-beta.creativecommons.org/

**Comment by royquilor** [comment]
> @royquilor a cool tool by creative commons to help decide your license : https://chooser-beta.creativecommons.org/

Thanks, will check it

**Comment by Jafner** [comment]
Could this be SVG'd and then added as a favicon for the site?
I've been working on building a landing page and I had to find this thread to get a clean Archivy logo png, then convert it to an SVG.

**Comment by Uzay-G** [comment]
I don't have an svg of the logo, unfortunately.

I'm curious about the landing page :)

**Comment by Jafner** [comment]
I'll share it with you on Discord once it's ready for publishing!
I'll also send you the svg. The original design was really nice and clean,
so converting it was dead easy and turned out nice.
