### ISSUE TITLE
Optional minimal markdown editor so people can edit files through the frontend

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#33]

**Comment by srevinsaju** [comment]
Cool open source browser markdown editor : https://stackedit.io/app#

**Comment by HarshaVardhanJ** [comment]
A few other suggestions:
* [Trix](https://github.com/basecamp/trix)
* [Quill](https://quilljs.com/docs/quickstart/)
* [Ace](https://ace.c9.io/#nav=about)

**Comment by clemux** [comment]
[simplemde](https://github.com/sparksuite/simplemde-markdown-editor) seems more "minimal" than the suggestions above

**Comment by Uzay-G** [comment]
Hmm, simplemde seems nice. Adding support for footnotes with some sort of extended markdown would also be nice.

**Comment by srevinsaju** [comment]
It looks better than the online Markdown editor provided by reddit. Looks cool

**Comment by Uzay-G** [comment]
We need to find something for this that we can embed into archivy. Something with inplace live preview like Marktext (https://github.com/marktext/marktext) would be amazing.

Marktext is electron-based, so maybe we could try to use it in the browser as it's a very nice editor.

**Comment by Uzay-G** [comment]
This is very nice: https://github.com/Jocs/muya-example but I think too big.
