### ISSUE TITLE
Brainstorm conversion of multiple formats and extension of current markdown

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#78]
I have started working on using pandoc's markdown to extend the current markdown parser. Locally, it now supports inline LaTeX, footnotes and tons of other extra features. 

I also wanted to try adding the possibility of importing .epub files. Now pandoc has a converter for this, and it can convert the text but it has a few issues with images and links. Here are those I've encountered:

- Image links are not correct and fail
- Hyperlinks to sections in books are also incorrect
- Speed - Loading a 1.4 MB markdown file is quite laggy for the browser

It also seems that pandoc does not support a pdf -> markdown converter.

Do you have ideas on how we could remedy these issues? Maybe keeping the file as a .epub and finding a way to view it like that?

Thoughts @clemux @srevinsaju @HarshaVardhanJ ?

**Comment by HarshaVardhanJ** [comment]
I think it would be fine if we didn't convert the EPUB file to markdown. Archivy serves as a knowledge base of sorts which contains a hodgepodge of different files and links. It would be sufficient to display the EPUB file in the browser.

Besides, EPUB is XHTML with CSS and fonts embedded in it. For example, opening the file with something like [Calibre](https://calibre-ebook.com) will show you the following:

 
![Screenshot 2020-09-03 at 15 58 52](https://user-images.githubusercontent.com/34051768/92104042-6af2e200-edfe-11ea-8a96-a5bb710bfc81.png)


![Screenshot 2020-09-03 at 16 00 52](https://user-images.githubusercontent.com/34051768/92104258-b4433180-edfe-11ea-8063-51fccecf25ad.png)

![Screenshot 2020-09-03 at 16 02 24](https://user-images.githubusercontent.com/34051768/92104446-f40a1900-edfe-11ea-89bd-c392e7a5c537.png)

So it's quite possible to display the file as it is in the browser. The HTML and CSS files embedded in the EPUB file are enough to display the file as a webpage.


Regarding the issue with the slow loading of a large markdown file, I'll have to try it before I make any suggestions.

**Comment by clemux** [comment]
> Regarding converting PDF to markdown, there's this library called pdf-to-markdown.

Not an option:

> This is NOT a general-purpose converter. Currently only for urban planning document in Taiwan.

Besides..

> I think it would be fine if we didn't convert the EPUB file to markdown. Archivy serves as a knowledge base of sorts which contains a hodgepodge of different files and links. It would be sufficient to display the EPUB file in the browser.

I agree, and I think that applies regarding of the format. Markdown is designed for writing documents, it is not a good intermediary representation between two formats.

- web pages: what is the reasoning behind converting them to markdown, only to render them as html+css? Maybe I'm missing something?

- epub documents : they don't need any processing to remove garbage like for web pages, we can use a custom css to display them differently

- pdf documents : they don't contain any structure, so any conversion would imply human and/or powerful AI processing

**Comment by HarshaVardhanJ** [comment]
> This is NOT a general-purpose converter. Currently only for urban planning document in Taiwan.

I see. My apologies.

>pdf documents : they don't contain any structure, so any conversion would imply human and/or powerful AI processing

I agree. It would be nice to add a parser of sorts in order to perform indexing and search. And structure information isn't necessary for this.

**Comment by Uzay-G** [comment]
The problem is that adding multiple formats increases code complexity by quite a bit and I'm not quite sure yet how we should structure things to cope with different formats cleanly.

**Comment by Uzay-G** [comment]
Any ideas?

**Comment by HarshaVardhanJ** [comment]
> The problem is that adding multiple formats increases code complexity by quite a bit and I'm not quite sure yet how we should structure things to cope with different formats cleanly.

I agree. Looking at the description of what Archivy is supposed to do, maybe importing different file formats isn't such a good idea. Keeping track of EPUB and PDF files falls into the domain of an ebook management application, which Archivy doesn't need to do.

**Comment by clemux** [comment]
That depends on whether archivy should be a backend for managing, reading and annotating documents, or a web page archiving application. 

In any case, I feel like limiting ourselves to web pages for now would be best, until we're comfortable adding a plug-in system for handling other file types in the store.

**Comment by Uzay-G** [comment]
Yes an extensible plug in system would allow us to add more optional
features without complexifying the code or the ux.

**Comment by Uzay-G** [comment]
Closing for now.
