### ISSUE TITLE
Implement plugin system that allows users to extend the way data is parsed and gathered

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#86]
Instead of adding code for a pocket integration, a much cleaner approach would be to build a plugin system that allows users to contribute their own modules that can gather and parse data in the way they like.

Linked to https://github.com/Uzay-G/archivy/issues/62 and https://github.com/Uzay-G/archivy/issues/34

**Comment by Uzay-G** [comment]
I'm not sure how to implement this - but this is the way I'd like to separate things:

- Tasks: These would be recurring events that would pull data. The pocket function could be refactored into one of these.
- Custom commands. Allow users to extend archivy with their own plugins that execute python code they wrote.


The idea would then be to allow users to publish their plugins to a package repository and the archivy web interface would have a plugin viewer.

If you have any idea on how we could go about implementing this system so users can flexibly, easily create plugins, that would be nice.

What could work is if we specify the `plugins` as cli commands with a defined set of arguments. Then, if a user wants to run a plugin from the web interface. We would simply add a form with the plugin's parameters and then run the script with the supplied arguments.

This is truly crucial for allowing extensibility and would solve many bottlenecks.

@srevinsaju @clemux @HarshaVardhanJ

**Comment by srevinsaju** [comment]
Perfect. Looks like a really cool and professional idea. Would you like to see plugins in `python` as the primary language? or do you want to support many programming languages?

If you are interested, you can see this https://github.com/srevinsaju/sugaroid/blob/8009ce7b8208521331aef4728db0640bdd35da22/sugaroid/sugaroid.py#L523
Here, I use dynamic plugins, as, "adapters" in my language. This will automatically run the statement through each of the adapter. It can be easily adjusted to the use case. We could dump the the list of plugins into a configuration file, and source them on the next startup.

**Comment by Uzay-G** [comment]
Yes it would be in python.

**Comment by Uzay-G** [comment]
A cool idea that could be implemented as a plugin or a built-in feature would be syncing archivy to a git repo which would also allow us to build a mobile client that syncs up to that.

**Comment by Uzay-G** [comment]
Interesting links:

- https://pluggy.readthedocs.io/en/latest/
- https://github.com/click-contrib/click-plugins

**Comment by Uzay-G** [comment]
Related to https://github.com/archivy/archivy/issues/131, I was wondering how we could make this system more flexible.

We could register "events" where plugin code is called. For example, whenever there is a file change on the watcher, we could register an event and our git plugin would commit the change.

I'm not sure how we should implement this.

One option would be to transform the yaml config file of #152 into a python config file where we could define events like this:

```python
class UserConfig():
	# user config
	# ...

	def on_file_change(dataobj):
		archivy_git.sync(dataobj)
		# ... whatever else the user wants to do

	def on_dataobj_creation(dataobj):
		...

```

This would allow more asynchronicity in the plugins which for now, can only be called as standalone commands.

What do you think of this idea?
