### ISSUE TITLE
Brainstorm ways in which Natural Language Processing can be used to imrove the experience with archivy

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#88]
Natural Language Processing is the domain of computer science that tries to help computers understand human text.

I think it can be used to make the process of saving and digitalizing one's thoughts and experiences easier - for example by summarizing data, automatically categorizing data - and grouping similar data.

Any ideas in which we can use this powerful science would be interesting :).

**Comment by rexdivakar** [comment]
Assign it to me i will add in @Uzay-G

**Comment by Uzay-G** [comment]
What would you like to add @rexdivakar? This is more of a discussion of the features we could add that are related to NLP. Is there something specific you'd like to work on?

**Comment by rexdivakar** [comment]
I can write a function to get the summarised version of the text also may be add in keyword extraction too. Let me know if u have anything specific in ur mind

**Comment by Uzay-G** [comment]
That would be cool! What would you use? Do you know [spacy](https://spacy.io). It's a really nice and efficient library that I have some experience with so it'd be cool if we could use it.

**Comment by rexdivakar** [comment]
Yeah I have some experience with spacy so I believe I can give it a shot

**Comment by Uzay-G** [comment]
This will be implemented with the plugin system later, unless anyone wants to give it a shot.
