### ISSUE TITLE
Other colour themes (dark)

### ISSUE THREAD

**Issue by Uzay-G** [archivy/archivy#89]
Look into the enabling other colour themes.

**Comment by bislara** [comment]
I would like to contribute to this for Hacktoberfest. Can you assign it to me? I can give a try for this.

**Comment by Uzay-G** [comment]
Alright! I'll assign you :).

**Comment by Uzay-G** [comment]
The redesign I implemented kind of removed the dark theme because the designs weren't compatible, but it'd be good to look into this again.

**Comment by Uzay-G** [comment]
It's now easier to implement one using the work of #228

**Comment by ropable** [comment]
I have some bandwidth to look at this issue unless @bislara is working on it.

**Comment by Uzay-G** [comment]
Yeah that would be nice! #228 is also related

**Comment by ropable** [comment]
PR #242 refers.

**Comment by Uzay-G** [comment]
Closed thanks to @ropable's great work !!
